language: ruby
before_install:
- gem install sass
branches:
  only: master
script: sass --scss --update scss:public/css
addons:
  ssh_known_hosts: $DEPLOY_HOST
before_deploy:
- openssl aes-256-cbc -K $encrypted_e64e26c049ef_key -iv $encrypted_e64e26c049ef_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy\_rsa
- ssh-add /tmp/deploy\_rsa
deploy:
- provider: s3
  region: eu-central-1
  local_dir: public
  access_key_id: AKIAJP2E4GO4OYLOEDHA
  secret_access_key:
    secure: VuC6IFSez+JPFJhBCS/f7qLtcZkjILV3dsqwy1V5IxKYLSKZT6UJjcqrRyNkb7YCGRL028XBcPP8K/YrCUJAPdDqrZ1hkC9vKiJuDnlTKVv6xVDsH9jkZwpu+M+vjRxe3NMEQoJrGPZ/LwNK3e5YrFqyjMAWKg6omNLlX6PAK9o/JEkpJ3PhEPOb78fOCWKOg4v87W7KA1GkzquVTJ8SHrqsQbYvDn2ZqsGo6sBidEU39pZTNhRW0qPGJK/EVaupeapKQV/6NpYHOonxG85ILkLXnxIvdzMoHuCbaeSbloJNnF9ZpYjDNYgoei4U7TcFSFuxidhI46/i6i2UEswvgjJZVEhA7wKwG0D+a2I6+4lzvOvI41tvGBNyibN97l23kaDh495uvmgmBTIX6/LZPAGpOQFdK+ivq2C/SjT1w+oAKcTi/PJFGst6843ZskswAQ053C7aTIYQRu0phvLatdE4bsCXUeAmFqg/N6tcbvCV06ldsUHXUC6e4armwWxob2Dl5GaLLJU0p62ZfPNyDRGXvTlLzHI5WzFrM588uq0p0ZvOx8yN4Btgq3twjjl3g5KHRTQeo/PX84MWUzFY1PrlEOZ+rroQq6PyS+bleC0WNWzuc/mqa0/SIW/CpzyGcmUQGd+mfUNYW6DA1Cg/lpwvysA52LMKYsf6273Ww4U=
  bucket: ohomburg.de
  acl: public_read
  on:
    repo: ohomburg/ohomburg.de
- provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after public/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    repo: ohomburg/ohomburg.de
env:
  global:
  - secure: avAHb4q3F3XjMr0vNRv/aNCAHsMVRcoaA7wUz0k0Fq0hIz0mGLE/WL/ckFvbFZ9gJMPzG/1mXw4WtZ0ulKgE+MeUPTVuBjo9JNTydqo/batbhdB1ABzbAQn2GVzxTHauq7/iE/491tlY0jvYY7sDRFDTV0lFPW0UUx87mN8aNqSfloR0bJML4EMPjB45euJMR9tZsjdsjJ6crL0jBpFmJfng14gEJBo7Vz26uK0nQuCbzFghdsASXqXI1NfZ8AcYUqMAhrwwMURPI4aLPV/UTJjQlBHYsbcN/ldFVc5u+KvPL003DjXiVKIRgwVhWoxVmKLg72xtREd3fh+v0j37cp4CXJgPDIlGUvm/SLZZka/vVpZ74N8D7REjt5RzBpNo6LXHs/eDvDAWPTVx9vTJmiwfv4alDdXLi7/upIpq8j3laxY6wXkcD7i3f7VEHOY+kfTwwAD9M+iqP/2nBVHnTFzsbxeUIivnJAZwHqRmTZjsTBe660n1rUBeZSvnb0qCBbbLpzRr6hE26eQAN3BNlPU+Wa1tMnEMwFab24IBSEi8QXYUOqAXa5zi0rdB/EeR/AwFZAyCDLIn/WTD4OZDG2VaSJmRF7KKnqdTc2+QaMYGLwiMTBZQLKqJ4i+n6TCk25Kmh7OpGRxvvCcURf0C0b5EUicbrjmh3NfwKWJ8EVU=
  - secure: oyE+NiF+70+4CugRBIDxmNqLBYamhWiABoa8cZFWrfpukgjU34EYSyhAU/RPxW0AAMGmSMNplsmNTmAhYLopgPqKu0v+DODG7aPWXSgFf4Ow8vuGgg9ymRi4prpBy/Iblz5vSz9YWk/zddD622jUIfw8Vfa/EDtuxfl/FyJ4U4FseYRpswwdOboEV6ixS+4UQUYDjQhZod8bQz0T9Nw52cvd++xnqj5VaOi1aDxB0SfGnuvoaLOiOMQe17UVd03lCDKDyJK8lihkAHpyvik5ejuZmJ5s7JeFBn/rA1ARznFJKEXLAQgDZBVeXGdHVtjQ9Xf++5uNAfFqyRfC2hpnb0dQ8jDkxe/JyEC2DNUgfrOeq6/H1NRoZGKwG0Jn0PW3sNsWUgSLuL0WxsEs+DaKNdjBog9IXhhEdzZwbEvX3dsCWwCSDIpXmrg3//qeGVVy9D3/oOrkdiCKx9zaQ6MSF+/ne0Ihw80jsVd2EbBNidbeWsTr2Pz4tMWfvo2u7ROXIl5H7m/snPJbsGINxKjwyQyRkKKLS53jffIwbtDS6bv8EVZDIWS23BK0xdgHjLnsuU15Laa7xXEwNGAe/EqRflMumKzpxhmswRR1d/aq6lwaTAQdZrHlPl8cONz7K7NPLM43FbToU+eJ4vGv2Gbg/jyIY8nP0MtH8a4KCcmf0oQ=
  - secure: wWlCZPkLfNm0JJ3ZeMRhfX6dmdN51+xni0tC8Jykz0ZbXlDtoGvn1z5vh5UNHM9xtxRNjVMDUoKkMorsxlMWDSk4eFQx03iXYcAdqXPN2SrLxj9hYENXjTZ5rVsUTbvcZbenYzBLuL49T64XCw4/0cP0fh1pSUaibIXlAjXIn372P5x54o0AxG6DBI2X7PDB0iHkWy6ripURBR+PO846HszML8dw4HWJlYxd1/uE3SYb6j/Q3GBvvV5Ndrc8ycQTD8ZETeSuIWLj5n0NMAvuh0haLAOGFTOmsa3hw/oVbK+pZRAL+IHpNPfI3szAOg9T4duoHket5U0hU/W5Ond47C9100gIBoPUpUo7tTquVyvI5+JL6oIxINZC5xVsQOTcH2gLaZJ+QYRcd4JIUhBgbo8dsZqgV+ws8PCnyXNkMIpu+o24XZsLV3DVXT2B5p2aAlHz9aBuWI93zqd4JEzRoiD1Ie8VlWK7XYpfRtuxxk1phk7hIWVi3Tu0duYm1RsCYJmcauM39AtWoBebwWooeYzQwDeYDu6tZOMPyeEpULveaumTdQ1Tn+xB20FPncRV6DQ5de1teB6v3RXzYqzaCaMyIiH2wNX5bSKnwBmEppRLCmWs3ZWjhLhHCpe8aavK+j2PhT5zstJ9TGXYMw8NMOCuRxQtEtkAtduhkG4w6+A=
